feat(undo): added -n flag for number option

diff --git a/dump b/dump
--- a/dump
+++ b/dump
@@ -116,7 +116,7 @@ function put() {
       mv -v "${file}" "${DUMP_DIR}"/"${file##*/}"
     else
       file_entry="${file##*/}-${dup_count}: $PWD/${file}"
-      mv -v "${file}" "${DUMP_DIR}"/"${file##*/}-${dup_count}"
+      mv -v "${file}" "${DUMP_DIR}/${file##*/}-${dup_count}"
     fi
     sed -i '' "s|${file_entry}||g" "${DUMP_LOG}"
     sed -i '' '/^[[:space:]]*$/d' "${DUMP_LOG}"
@@ -125,22 +125,23 @@ function put() {
 }
 
 #######################################
-# regret(undo) a file, move a file from dump to it's original location
+# undo a file, move a file from dump to it's original location
 # Arguments:
 #   -h|--help: show help message and exit
 #   -i|--confirm: prompt confirmation on each file
 #   -s|--select: use fzf to select a file to revert
 #   -l|--local: reset file to current location
-#   $*: all the no flag command line argument are parsed as files to regret
+#   $*: all the no flag command line argument are parsed as files to undo
 #######################################
-function regret() {
-  local file_to_revert fuzzy confirm_prompt confirm_result regret_location files_to_revert force_overwrite
+function undo() {
+  local file_to_revert fuzzy confirm_prompt confirm_result undo_location files_to_revert force_overwrite revert_count
   files_to_revert=()
-  regret_location="original"
+  undo_location="original"
+  revert_count=1
   while [[ $# -gt 0 ]]; do
     case "$1" in
       -l|--local)
-        regret_location="local"
+        undo_location="local"
         shift
         ;;
       -h|--help)
@@ -159,6 +160,13 @@ function regret() {
         force_overwrite="true"
         shift
         ;;
+      -n|--num)
+        [[ -z "$2" ]] && echo "Invalid option: $1" >&2 && usage && exit 1
+        revert_count=$(($2))
+        [[ "${revert_count}" -lt 1 ]] && usage && exit 1
+        shift
+        shift
+        ;;
       *)
         files_to_revert=("$@")
         break
@@ -171,7 +179,7 @@ function regret() {
     file_line="$1"
     file_name="${file_line%%: *}"
 
-    case "${regret_location}" in
+    case "${undo_location}" in
       "original")
         file_path="${file_line##*: }"
         ;;
@@ -184,7 +192,7 @@ function regret() {
     esac
 
     [[ -n "${confirm_prompt}" ]] \
-      && confirm_result=$(get_confirm "regret: reset ${file_name} to ${file_path}?") \
+      && confirm_result=$(get_confirm "undo: reset ${file_name} to ${file_path}?") \
       && [[ "${confirm_result}" != "y" ]] \
       && return
 
@@ -223,11 +231,15 @@ function regret() {
     done
 
   else
-    file_to_revert=$(tail -r -n 1 "${DUMP_LOG}")
-    [[ -z "${file_to_revert}" ]] \
+    while IFS= read -r line; do
+      files_to_revert+=("${line}")
+    done < <(tail -r -n "${revert_count}" "${DUMP_LOG}")
+    [[ "${#files_to_revert[@]}" -eq 0 ]] \
       && echo "No file to reset" \
       && exit 1
-    _move_file "${file_to_revert}"
+    for file_to_revert in "${files_to_revert[@]}"; do
+      _move_file "${file_to_revert}"
+    done
   fi
 }
 
@@ -281,7 +293,7 @@ function clean() {
       file_to_clean=$(grep -xE "^$file.*$" "${DUMP_LOG}" | tail -r -n 1)
       file_name="${file_to_clean%%: *}"
       file_path="${file_to_clean##*: }"
-      [[ -z "${files_to_clean}" ]] \
+      [[ -z "${file_to_clean}" ]] \
         && echo "File not found in dump log" \
         && continue
       [[ -n "${confirm_prompt}" ]] \
@@ -342,14 +354,14 @@ function log() {
         BEGIN { printf "%-31s %-40s\n", "Name", "Location" }
         { printf "%-30s %-40s\n", $1, $2}
       ' \
-    | ([[ -n "${pager}" ]] && less || cat)
+    | (if [[ -n "${pager}" ]]; then less; else cat; fi)
 }
 
 #######################################
 # print usage of dump-cli
 #######################################
 function usage() {
-  echo -e "Usage: dump [-h] [-p] [-c] [-r] [-l] [FILE] [OPTIONS] ...
+  echo -e "Usage: dump [-h] [-p] [-c] [-u] [-l] [FILE] [OPTIONS] ...
 
 A simple to use trash utility which persist the dumped file and it's original
 location for future undos. Integrated with fzf for interactive selection of the
@@ -383,8 +395,9 @@ Optional arguments:
   Optional arguments:
     -i, --confirm\t\tprompt confirmation before dumping each file.
     -s, --select\t\tselect a file to undo through fzf.
-    -l, --local\t\treset file to current location.
-    -f, --force\t\tforce overwrite even if undo file already existed.
+    -l, --local\t\t\treset file to current location.
+    -f, --force\t\t\tforce overwrite even if undo file already existed.
+    -n [NUM], --num [NUM]\tspecify number of files to undo.
 
   Example:
     dump --undo hello.java hello.py bin
@@ -427,7 +440,7 @@ case $1 in
     shift
     ;;
   --undo|-u)
-    action_comand='regret'
+    action_comand='undo'
     shift
     ;;
   --log|-l)
